# Standalone Pipeline to run Automated API tests
# Using rsp-iras-api-tests repo

name: Run API Tests

variables:
  CI: true

trigger:
- main

jobs: 
  - job: Run_Automated_API_Tests
    timeoutInMinutes: 10
    pool:
      vmImage: ubuntu-latest
     
    steps:
      - task: Npm@1
        displayName: 'Install Dependencies'
        inputs:
          command: custom
          verbose: false
          customCommand: 'install newman -g'

      - script: |
          newman run $(System.DefaultWorkingDirectory)/rsp-iras-api-tests/postmancollection/postman_collection.json -x -r junit --reporter-junit-export $(System.DefaultWorkingDirectory)/rsp-iras-api-tests/TestResults/API_Test_Report.xml
        displayName: 'Run Postman API Tests'

      - task: PublishBuildArtifacts@1
        displayName: Publish API Test Report
        inputs:
          PathtoPublish: '$(System.DefaultWorkingDirectory)/rsp-iras-api-tests/TestResults'
          ArtifactName: 'API_Test_Report.xml'
          publishLocation: 'Container'