# Standalone Pipeline to run Automated API tests
# Using rsp-iras-api-tests repo

name: Run API Tests

trigger:
  - main

schedules:
  - cron: '0 0 * * Mon-Fri'
    displayName: 'Nightly run - full suite'
    branches:
      include: 
      - main

pool:
  vmImage: "Ubuntu-latest"

parameters:
  - name: devops_library_branch
    displayName: DevOps Library Branch
    type: string
    default: main

resources:
  repositories:
    - repository: library
      type: git
      name: DevOps/rsp-azure-devops-library
      ref: ${{ parameters.devops_library_branch }}

stages:
  - stage: APIPostmanTests
    displayName: API Postman Tests
    jobs:
      - template: jobs/api_tests.yaml@library