# Standalone Pipeline to run Automated API tests
# Using rsp-iras-api-tests repo

name: Run API Tests

variables:
  CI: true

trigger:
- main

jobs: 
  - job: Run_Automated_API_Tests
    timeoutInMinutes: 10
    pool:
      vmImage: ubuntu-latest
     
    steps:
      - task: Npm@1
        displayName: 'Install Dependencies'
        inputs:
          command: custom
          verbose: false
          customCommand: 'install newman -g'

      - script: |
          npm install -g newman-reporter-htmlextra
        displayName: 'Install Dependency to generate HTML API report'

      - script: |
          newman run $(Build.Repository.LocalPath)/postmancollection/postman_collection.json -r html --reporter-html-export TestResults/API_Test_Report.html
        displayName: 'Run Postman API Tests'

      - task: PublishBuildArtifacts@1
        displayName: Publish API Test Report
        condition: always()
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/TestResults'
          ArtifactName: 'API_Test_Report'
          publishLocation: 'Container'